Pod::Spec.new do |s|
  s.name         = "MezonModule"
  s.version      = "1.0.0"
  s.summary      = "Mezon Proto Native Module"
  s.homepage     = "https://mezon.ai"
  s.license      = "MIT"
  s.authors      = { "Mezon Team" => "hello@mezon.vn" }
  s.platforms    = { :ios => "14.0" }
  s.source       = { :path => "." }

  # Link the XCFramework generated by your Makefile
  s.vendored_frameworks = "Mezon.xcframework"
  
  # Standard React Native dependencies
  s.dependency "React-Core"
  
  # Ensure C++ features are enabled
  s.pod_target_xcconfig = {
    "CLANG_CXX_LANGUAGE_STANDARD" => "c++17",
    "OTHER_LDFLAGS" => "-lstdc++ -lpthread"
  }
end